### ISSUE TITLE
Fix encodingFormat explaination + example SPARQL-endpoint

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-register#984] opened 2024-08-26 19:15 UTC
The description of `schema:encodingFormat` currently reads:

> The distribution’s MIME format, for example application/sparql-query for a SPARL endpoint or application/ld+json for a data dump serialized as JSON-LD. Use a value from the [[IANA-MEDIA-TYPES]](https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/#biblio-iana-media-types) list. 

The [full example](https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/#dataset-example) includes:

>      {
>       "@type": "DataDownload",
>       "encodingFormat": "application/sparql-query",
>       "contentUrl": "http://data.bibliotheken.nl/sparql",
>       "dateCreated": "2023-06-01T08:00:00+01:00",
>       "dateModified": "2024-03-04T01:09:00+01:00"
>     }

But `application/sparql-query` is wrong and should be removed. This format is to be used for SPARQL _queries_, not SPARQL _responses_, see https://www.w3.org/TR/2006/WD-rdf-sparql-query-20060220/mime.txt

The correct encodingFormat (aka MIME type of Media Type) would be `application/sparql-results+xml`, `application/sparql-results+json`, `application/x-binary-rdf-results-table` (or `application/n-quads` etc for SPARQL constructs) and should be as described with `schema:encodingFormat`:
> The value should indicate the Media type of the response of the schema:contentUrl when no Accept header is included in the request. 

Creators of datasetdescriptions should be aware that there is no standard encodingFormat for an SPARQL-endpoint defined. GraphDB and Virtuoso seems to default to `application/sparql-results+xml`, Apache Fuseki to `application/sparql-results+json` and TriplyDB to `application/json` (should that not be `application/sparql-results+json`??).

SPARQL endpoints let you specify the desired output via the HTTP Accept header. But an Accept header cannot be expressed in the datasetdescription. Alternatively a user can include a HTTP parameter in the `schema:contentUrl`. As this is not standardized, each vendor uses a different parameter. For example: with GraphDB you can add the Accept parameter in the URL ([example](https://www.goudatijdmachine.nl/sparql/repositories/gtm?query=PREFIX+gtm%3A+%3Chttps%3A%2F%2Fwww.goudatijdmachine.nl%2Fdef%23%3E%0D%0Aselect+*+where+%7B%0D%0A++++%3Fs+a+gtm%3AStraat%0D%0A%7D+limit+100&infer=true&sameAs=true&Accept=application%2Fsparql-results%2Bjson)), with Virtuose with the format parameter ([example](https://data.bibliotheken.nl/sparql?default-graph-uri=&query=select+distinct+%3FConcept+where+%7B%5B%5D+a+%3FConcept%7D+LIMIT+10&format=text%2Fturtle&timeout=0&debug=on&run=+Run+Quer)). Unsure if TriplyDB and Fuseki have these this ability.

There are currently [102 datasetsdescriptions](https://datasetregister.netwerkdigitaalerfgoed.nl/search.php#eyJmIjpbImFwcGxpY2F0aW9uL3NwYXJxbC1xdWVyeSJdLCJ0IjoiIn0=) which uses `application/sparql-query`, only [13 datasetdescriptions](https://datasetregister.netwerkdigitaalerfgoed.nl/search.php#eyJmIjpbImFwcGxpY2F0aW9uL3NwYXJxbC1yZXN1bHRzK2pzb24iXSwidCI6IiJ9) which use `application/sparql-results+json` and none use `application/sparql-results+xml`. The creators of these 102 datasetdescriptions should be notified about the wrong value in `schema:encodingFormat`.

**Comment by ddeboer** [comment] 2024-08-27 11:31
Duplicate of https://github.com/netwerk-digitaal-erfgoed/requirements-datasets/issues/67.

**Closed by ddeboer** 2024-08-27 11:31 UTC
