### ISSUE TITLE
schema:encodingFormat validation

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-register#333] opened 2021-11-10 10:40 UTC
@EnnoMeijers noted the use of the Media Type "application/turtle" in schema:encodingFormat properties. "application/turtle" is not on the [IANA list of Media Types](https://www.iana.org/assignments/media-types/).

The current [Requirements for Datasets](https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/#distribution-attributes) states:

> The distribution’s MIME format, for example application/sparql-query for a SPARL endpoint or application/ld+json for a data dump serialized as JSON-LD. See [IANA-MEDIA-TYPES] and MDN-reference for more information.

Currenlty, the SHACL validation only checks if there is a one (and only one) value for `schema:encodingFormat`, otherwise a Violation is raised.

To help produce better dataset descriptions, which adhere to standards, a Warning should be given during validation if the `schema:encodingFormat` property does not contain a value which is on the [IANA list of Media Types](https://www.iana.org/assignments/media-types/)

**Comment by coret** [comment] 2021-11-10 10:50
Another value used by dataset publishers is "text/xml". This value isn't on the [IANA list of Media Types](https://www.iana.org/assignments/media-types/) either.

There seems to be a registration for "text/xml" in [XML Media Types](https://www.rfc-editor.org/rfc/rfc7303) ...

**Comment by ddeboer** [comment] 2021-11-10 13:09
Duplicate of #177.

**Closed by ddeboer** 2021-11-10 13:09 UTC
